### ISSUE TITLE
when install with pwa optimization plugin.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-http2-optimization#2]
in the http2 plugin it keep saying.

Cache-Digest | Install the PWA Optimization plugin to use this feature.

when the PWA plugin is install. maybe remove it or have something that saying activated or show option that ca be used.

![image](https://user-images.githubusercontent.com/21690761/39658981-92444eb4-4fec-11e8-955c-1fb6a9607596.png)

**Comment by mxmkmarquette** [comment]
what is the purpose to show this...

![image](https://user-images.githubusercontent.com/21690761/39955655-aa4c3ea4-55a0-11e8-9280-8fa56eb9a090.png)


like even if the pwa plugin is install it keep showing and telling this.

**Comment by optimalisatie** [comment]
Hi @mxmkmarquette,

More info is available in the Wiki:

https://github.com/o10n-x/wordpress-http2-optimization/wiki/HTTP-2-Server-Push-vs-Service-Worker-Push
