### ISSUE TITLE
push and CDN?

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-http2-optimization#3]
Hiya,
Can server push be used with CDN?
Can you give an example of the json config?
Cheers! :-)

**Comment by ProductivePhysician** [comment]
Hi team, any suggestions?

**Comment by ahmed-sigmalux** [comment]
HTTP/2 push is restricted to same-origin resources.

**Comment by optimalisatie** [comment]
Hi @ProductivePhysician,

@ProductivePhysician is correct. 

Our **Service Worker Push** innovation however can push any URL, including a CDN and it has a much better performance (it supports >1 million URLs and doesn't require complex cache digest calculation to save bandwidth).

More info is in the Wiki:

https://github.com/o10n-x/wordpress-http2-optimization/wiki
