### ISSUE TITLE
Option to limit the preloaded asset to a specific page via JSON

### ISSUE THREAD

**Issue by pra85** [o10n-x/wordpress-http2-optimization#6]
Currently, when an asset is preloaded by adding into the JSON configuration, it gets preloaded globally on every page. 

Would it be possible to introduce an option in the JSON config itself which allows us to limit where the asset is preloaded so that it is easier to manage from a single location?

**Comment by optimalisatie** [comment]
Hi pra85,

Thank you very much for your feedback!

Conditional JSON was planned for a more advanced version of the plugin. The current WPO plugins use WordPress options to store the JSON configuration in a global (site based) way.

We are considering to add conditional JSON configuration to thw WPO plugins using a PHP method. Please let us know if this would be an solution for your use case.

```php
# conditionally set config by key
\O10n\config('css.async.enabled', false);

# conditionally set config by multiple keys
\O10n\config(array(
    'css.async.enabled' => false
));

# conditionally set config by JSON array
\O10n\config(array(
    'css' => array(
        'async' => array(
            'enabled' => false
        )
    )
), true);

# input raw JSON config (string)
\O10n\config(file_get_contents('path/to/custom-conditional-config.json'));
```

**Comment by optimalisatie** [comment]
The conditional config option has been added in the latest update. Please let us know if this provides a solution for your use case.

**Comment by optimalisatie** [comment]
In regards to a solution, you could also look into creating a stealth custom optimization plugin, for example using the `mu-plugin` folder.

https://codex.wordpress.org/Must_Use_Plugins

The custom plugin could be very simple. It would simply add a WordPress action hook that conditionally applies optimization configuration.

In a more advanced concept you could store the optimization config in physical JSON files. This would make it possible to update the settings from a local editor (with auto upload) making it very efficient for fine tuning settings. An update would cost a second compared to using + saving a WordPress admin panel.

### Example 

Plugin: `mu-plugins/Custom_Named_Optimization.php`

```php
<?php
/**
 * Plugin Name: Custom Named Optimization
 * Description: Custom optimization configuration.
 * Author:      Your Name
 * License:     GNU General Public License v3 or later
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */

// security
if (!defined( 'ABSPATH' ) { die( 'Forbidden' ); }

// plugin path
define('CUSTOM_O10N_PLUGIN_PATH') = dirname(__FILE__);

// conditional optimization JSON config
add_action('init', function () {

	$config_dirs = array();

	// AMP pages
	if (is_amp_endpoint()) {

		$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/amp/';

	} else {

		// load global config for all pages
		$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/global/';

		if (is_page([1,5,19])) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/special-page/';
		} else if (is_page()) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/page/';
		} else if (is_single()) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/post/';
		}

	}

	// walk config directories in defined order
	foreach ($config_dirs as $dir) {

		// read config directory
		$files = new \FilesystemIterator($dir, \FilesystemIterator::SKIP_DOTS);
		foreach ($files as $fileinfo) {

			// verify file
			if (!$fileinfo->isFile() || $fileinfo->getExtension() !== 'json') {
				continue;
			}

			// load config
			\O10n\config(file_get_contents($dir . $fileinfo->getFilename()));
		}
	}

}, 10, 0);
```
